import type { AdminPlannedEndpoint, AdminRouteDoc } from "@/lib/admin-types"

export const ADMIN_ROUTE_CATALOG: AdminRouteDoc[] = [
  {
    path: "/api/home",
    methods: ["GET"],
    audience: "public",
    summary: "Homepage market snapshot with featured carousel, live lists, insights, and activity feed.",
    response: {
      description: "HomepageSnapshot",
      example: {
        featuredCarousel: [{ twin: { id: "0x...", displayName: "Twin Alpha" }, source: "auto" }],
        latestTwins: [{ id: "0x...", displayName: "Twin Alpha", lastPriceUsd: 12.4 }],
        newTwins: [{ id: "0x...", displayName: "Twin Beta", ageLabel: "14m" }],
        insights: [{ id: "insight-1", title: "Momentum building", tone: "bullish" }],
        activity: [{ id: "trade-1", twinId: "0x...", trader: "0xabc...def0", usdAmount: 340 }],
      },
    },
    dataSources: ["twins", "twin_metadata", "homepage_snapshot_cache", "featured-override.json"],
    uiCapabilities: ["Homepage polling", "Operational health visibility"],
  },
  {
    path: "/api/twins/trending",
    methods: ["GET"],
    audience: "public",
    summary: "Top market twins ranked by indexed volume and trade activity.",
    response: {
      description: "Trending twins list",
      example: { twins: [{ id: "0x...", displayName: "Twin Alpha", volume24hUsd: 18420 }] },
    },
    dataSources: ["twins", "twin_metadata"],
    uiCapabilities: ["Market list rendering"],
  },
  {
    path: "/api/twins/new",
    methods: ["GET"],
    audience: "public",
    summary: "Newest indexed twins for launch discovery surfaces.",
    response: {
      description: "New twins list",
      example: { twins: [{ id: "0x...", displayName: "Twin Beta", ageLabel: "9m" }] },
    },
    dataSources: ["twins", "twin_metadata"],
    uiCapabilities: ["Fresh launches grid"],
  },
  {
    path: "/api/twins/featured",
    methods: ["GET"],
    audience: "public",
    summary: "Featured twin selection after admin override, env default, or automatic ranking.",
    response: {
      description: "Featured twin payload",
      example: { twin: { id: "0x...", displayName: "Twin Alpha" }, source: "admin" },
    },
    dataSources: ["featured-override.json", "FEATURED_TWIN_ID", "twins", "twin_metadata"],
    uiCapabilities: ["Homepage hero selection"],
  },
  {
    path: "/api/twins/search",
    methods: ["GET"],
    audience: "public",
    summary: "Query indexed twins by id, name, or description text.",
    query: [{ name: "q", required: true, description: "Free-text twin search query." }],
    response: {
      description: "Search results",
      example: { results: [{ id: "0x...", displayName: "Twin Alpha", owner: "0xdef..." }] },
    },
    dataSources: ["twins", "twin_metadata"],
    uiCapabilities: ["Search bars", "Entity resolution"],
  },
  {
    path: "/api/twins/[id]",
    methods: ["GET"],
    audience: "public",
    summary: "Twin detail summary for a single twin id.",
    response: {
      description: "TwinSummary",
      example: { id: "0x...", displayName: "Twin Alpha", holders: 187, lastPriceUsd: 15.1 },
    },
    dataSources: ["twins", "twin_metadata", "twin_detail_snapshot_cache"],
    uiCapabilities: ["Twin detail header", "Featured live refresh"],
  },
  {
    path: "/api/twins/[id]/quote",
    methods: ["GET"],
    audience: "public",
    summary: "Live buy/sell quote for a twin and amount, optionally scoped to wallet holdings.",
    query: [
      { name: "amount", required: false, description: "Whole-number key amount, default 1." },
      { name: "wallet", required: false, description: "Wallet address for holder-aware quote fields." },
    ],
    response: {
      description: "TwinQuote",
      example: {
        twinId: "0x...",
        amount: "1",
        buyQuoteUsd: "18.24",
        sellQuoteUsd: "17.91",
        holderBalance: "3",
      },
    },
    dataSources: ["BSC_RPC_URL", "contract read"],
    uiCapabilities: ["Trade panel", "Quick buy"],
  },
  {
    path: "/api/twins/create",
    methods: ["GET"],
    audience: "public",
    summary: "Creation quote for a prospective twin id.",
    query: [{ name: "id", required: true, description: "0x-prefixed bytes16 twin id." }],
    response: {
      description: "TwinCreationQuote",
      example: {
        twinId: "0x85f4f72079114bfcac1003134e5424f4",
        exists: false,
        minSharesToCreate: "10",
        requiredValueUsd: "124.81",
      },
    },
    dataSources: ["BSC_RPC_URL", "contract read"],
    uiCapabilities: ["Create twin flow"],
  },
  {
    path: "/api/portfolio",
    methods: ["GET"],
    audience: "wallet",
    summary: "Portfolio positions, concentration, liquidity, and derived insights for a wallet.",
    query: [{ name: "account", required: true, description: "Wallet address." }],
    response: {
      description: "PortfolioSnapshot",
      example: {
        account: "0xabc...def0",
        positions: [{ twin: { id: "0x...", displayName: "Twin Alpha" }, heldKeys: 4 }],
        portfolioValueUsd: 1420.33,
      },
    },
    dataSources: ["wallet holdings", "twins", "watchlists", "quotes"],
    uiCapabilities: ["Portfolio screen"],
  },
  {
    path: "/api/wallet/balance",
    methods: ["GET"],
    audience: "wallet",
    summary: "Native BNB balance and USD conversion for a wallet.",
    query: [{ name: "account", required: true, description: "Wallet address." }],
    response: {
      description: "Balance snapshot",
      example: { account: "0xabc...def0", wei: "1200000000000000000", bnb: 1.2, usd: 784.44 },
    },
    dataSources: ["BSC_RPC_URL", "BNB/USD price feed"],
    uiCapabilities: ["Portfolio cash balance"],
  },
  {
    path: "/api/wallet/session",
    methods: ["GET", "POST", "PUT", "DELETE"],
    audience: "wallet",
    summary: "Signed wallet-verification challenge and session cookie flow for account-scoped persistence routes.",
    query: [{ name: "account", required: false, description: "Optional wallet address when checking session status." }],
    requestBody: {
      description: "Challenge or verification payload",
      example: {
        account: "0xabc...def0",
        nonce: "b8f1f4f1-....",
        signature: "0x1234...",
      },
    },
    response: {
      description: "Session status or issued challenge",
      example: { authenticated: true, account: "0xabc...def0", expiresAt: "2026-04-03T12:00:00.000Z" },
    },
    dataSources: ["HttpOnly wallet session cookie", "in-memory wallet challenge store"],
    uiCapabilities: ["Wallet-scoped settings auth"],
  },
  {
    path: "/api/watchlist",
    methods: ["GET", "POST", "DELETE"],
    audience: "wallet",
    summary: "Read and mutate persisted watchlist entries for a wallet.",
    query: [{ name: "account", required: false, description: "Required on GET as wallet address." }],
    requestBody: {
      description: "Add/remove watchlist payload",
      example: { account: "0xabc...def0", twinId: "0x..." },
    },
    response: {
      description: "Persisted watchlist",
      example: { items: [{ id: "0x...", displayName: "Twin Alpha" }] },
    },
    dataSources: ["user_watchlists", "twins", "twin_metadata", "wallet session"],
    uiCapabilities: ["Watchlist toggle", "Watchlist page"],
  },
  {
    path: "/api/watchlist/dashboard",
    methods: ["GET"],
    audience: "wallet",
    summary: "Watchlist dashboard cards enriched with quotes, insight, and sparkline trend data.",
    query: [{ name: "account", required: true, description: "Wallet address." }],
    response: {
      description: "Watchlist dashboard snapshot",
      example: {
        items: [{ twin: { id: "0x...", displayName: "Twin Alpha" }, quote: { amount: "1" } }],
      },
    },
    dataSources: ["user_watchlists", "twins", "quotes", "twin_detail_snapshot_cache", "wallet session"],
    uiCapabilities: ["Watchlist dashboard UI"],
  },
  {
    path: "/api/settings/quick-buy",
    methods: ["GET", "POST"],
    audience: "wallet",
    summary: "Read and persist the wallet-level quick-buy amount.",
    query: [{ name: "account", required: false, description: "Required on GET as wallet address." }],
    requestBody: {
      description: "Quick-buy write payload",
      example: { account: "0xabc...def0", quickBuyAmount: 3 },
    },
    response: {
      description: "Saved quick-buy amount",
      example: { quickBuyAmount: 3 },
    },
    dataSources: ["user_trade_preferences", "wallet session"],
    uiCapabilities: ["Settings form"],
  },
  {
    path: "/api/alerts",
    methods: ["GET", "POST"],
    audience: "wallet",
    summary: "List or create wallet-level alerts for price, volume, and holder changes.",
    query: [{ name: "account", required: false, description: "Required on GET as wallet address." }],
    requestBody: {
      description: "Alert creation payload",
      example: {
        account: "0xabc...def0",
        twinId: "0x...",
        conditionType: "price_above",
        threshold: 22.5,
        windowMinutes: 60,
      },
    },
    response: {
      description: "Alerts collection or created alert",
      example: {
        alerts: [{ id: 12, label: "price_above alert", status: "active" }],
        alert: { id: 12, status: "active" },
      },
    },
    dataSources: ["user_alerts", "twins", "wallet session"],
    uiCapabilities: ["Alert management surfaces"],
  },
  {
    path: "/api/alerts/[id]",
    methods: ["PATCH", "DELETE"],
    audience: "wallet",
    summary: "Update or delete a single wallet alert.",
    requestBody: {
      description: "Alert patch payload",
      example: { account: "0xabc...def0", status: "paused", threshold: 19.5 },
    },
    response: {
      description: "Updated alert or ok flag",
      example: { alert: { id: 12, status: "paused" }, ok: true },
    },
    dataSources: ["user_alerts", "wallet session"],
    uiCapabilities: ["Alert editor"],
  },
  {
    path: "/api/ai/copilot",
    methods: ["POST"],
    audience: "wallet",
    summary: "Copilot orchestration route with trace logging and prompt review capture.",
    requestBody: {
      description: "Copilot prompt payload",
      example: {
        prompt: "Compare Alpha and Beta",
        account: "0xabc...def0",
        twins: [{ id: "0x...", displayName: "Twin Alpha", owner: "0xdef..." }],
        debug: true,
      },
    },
    response: {
      description: "CopilotResult with optional debug block",
      example: {
        prompt: "Compare Alpha and Beta",
        traceId: "copilot-1711978123-a1b2c3",
        provider: "OpenGradient",
        responseMode: "comparison",
      },
    },
    dataSources: ["OPENGRADIENT_*", "copilot-trace.ndjson", "copilot_prompt_reviews", "twins"],
    uiCapabilities: ["AI copilot console", "Admin trace review"],
  },
  {
    path: "/api/image",
    methods: ["GET"],
    audience: "public",
    summary: "Host-restricted HTTPS image proxy used by twin cards and detail surfaces.",
    query: [{ name: "url", required: true, description: "Allowed remote image URL." }],
    response: {
      description: "Binary image stream",
      example: { contentType: "image/png", cacheControl: "public, max-age=3600, ..." },
    },
    dataSources: ["IMAGE_PROXY_ALLOWED_HOSTS"],
    uiCapabilities: ["Image rendering"],
  },
  {
    path: "/api/telemetry",
    methods: ["POST"],
    audience: "public",
    summary: "Best-effort client telemetry sink for wallet-connect and transaction-submission failures.",
    requestBody: {
      description: "Client telemetry event payload",
      example: {
        name: "wallet_connect_failure",
        message: "User rejected the wallet connection request.",
        data: { flow: "wallet-provider" },
      },
    },
    response: {
      description: "Telemetry acknowledgement",
      example: { ok: true },
    },
    dataSources: ["ops-events.ndjson"],
    uiCapabilities: ["Admin reliability dashboard"],
  },
  {
    path: "/api/admin/featured",
    methods: ["GET", "POST", "DELETE"],
    audience: "admin",
    summary: "Inspect, set, or clear the homepage featured override.",
    requestBody: {
      description: "Featured override write payload",
      example: { twinId: "0x85f4f72079114bfcac1003134e5424f4", label: "Admin Pick" },
    },
    response: {
      description: "Override state",
      example: { override: { twinId: "0x...", label: "Admin Pick", updatedAt: "2026-04-02T12:00:00.000Z" } },
    },
    dataSources: ["featured-override.json"],
    uiCapabilities: ["Admin featured control"],
  },
  {
    path: "/api/admin/copilot-reviews",
    methods: ["GET"],
    audience: "admin",
    summary: "List recent copilot prompt reviews for clarification and error triage.",
    query: [
      { name: "status", required: false, description: "Filter open, reviewed, or ignored." },
      { name: "limit", required: false, description: "Max review count, defaults to 50." },
    ],
    response: {
      description: "Review queue",
      example: { reviews: [{ id: 31, reason: "clarification_required", status: "open" }] },
    },
    dataSources: ["copilot_prompt_reviews"],
    uiCapabilities: ["Review queue management"],
  },
  {
    path: "/api/admin/copilot-reviews/[id]",
    methods: ["PATCH"],
    audience: "admin",
    summary: "Update review queue status for a single copilot prompt review.",
    requestBody: {
      description: "Review status patch payload",
      example: { status: "reviewed" },
    },
    response: {
      description: "Updated review",
      example: { review: { id: 31, status: "reviewed", reviewedAt: "2026-04-02T12:02:00.000Z" } },
    },
    dataSources: ["copilot_prompt_reviews"],
    uiCapabilities: ["Review queue management"],
  },
  {
    path: "/api/admin/health",
    methods: ["GET"],
    audience: "admin",
    summary: "Active dependency health checks for Postgres, BSC RPC, subgraph, and AI/copilot dependencies.",
    response: {
      description: "Dependency health snapshot",
      example: {
        overallStatus: "degraded",
        checks: [
          { target: "database", status: "ok", latencyMs: 14 },
          { target: "bsc-rpc", status: "degraded", latencyMs: 842 },
        ],
      },
    },
    dataSources: ["database", "BSC_RPC_URL", "SUBGRAPH_URL", "PYTHON_BIN", "OPENGRADIENT_PRIVATE_KEY"],
    uiCapabilities: ["Admin readiness panel"],
  },
  {
    path: "/api/admin/overview",
    methods: ["GET"],
    audience: "admin",
    summary: "Aggregated admin snapshot for routes, env state, operational data, logs, and control surfaces.",
    response: {
      description: "AdminOverview",
      example: {
        generatedAt: "2026-04-02T12:05:00.000Z",
        auth: { configured: true, usernameHint: "ad***" },
        database: { configured: true, tables: [{ name: "twins", rowCount: 812 }] },
      },
    },
    dataSources: ["admin helpers", "database", "filesystem artifacts", "route catalog"],
    uiCapabilities: ["Admin console refresh"],
  },
]

export const ADMIN_PLANNED_ENDPOINTS: AdminPlannedEndpoint[] = [
  {
    path: "/api/admin/sync-runs",
    methods: ["GET"],
    summary: "Dedicated sync-run history explorer.",
    purpose: "Expose catalog ingests, browser collection runs, and retry/failure diagnostics without opening the database directly.",
    responseExample: {
      runs: [{ id: 51, source: "twinfun-indexer", mode: "incremental", status: "failed" }],
    },
  },
  {
    path: "/api/admin/cache",
    methods: ["GET", "DELETE"],
    summary: "Cache introspection and invalidation for homepage and twin-detail caches.",
    purpose: "Let the admin UI inspect stale data windows and trigger safe cache clears when feeds degrade.",
    responseExample: {
      homepage: { failureCount: 1, lastSuccessAt: "2026-04-02T11:58:00.000Z" },
      twinDetails: { entryCount: 124 },
    },
  },
  {
    path: "/api/admin/data-explorer",
    methods: ["POST"],
    summary: "Read-only table explorer with fixed allowlist and pagination.",
    purpose: "Inspect watchlists, alerts, quick-buy settings, and metadata rows without direct SQL shell access.",
    requestExample: { table: "user_alerts", page: 1, pageSize: 25 },
    responseExample: { rows: [{ id: 12, status: "active" }], total: 184 },
  },
  {
    path: "/api/admin/logs",
    methods: ["GET"],
    summary: "Structured log tail and stage filters beyond the copilot trace file.",
    purpose: "Centralize operational logs once more routes emit structured events.",
    responseExample: {
      entries: [{ timestamp: "2026-04-02T12:10:00.000Z", scope: "watchlist", level: "error" }],
    },
  },
]
